### ISSUE TITLE
更改图片

### ISSUE THREAD

**Issue by yangqinj** [skylarklxlong/skylarklxlong.github.io#1]
你好，请问一下要如何修改标签上面的那个小头像呢？我尝试修改了favcon文件，但是还是不行。

另外，我在_config.yml中，将url设置为自己的地址之后，点击“关于我”，“所有文章”，“标签”就会出错了。
 > url: "https://yangqinj.github.io/"

谢谢。

**Comment by skylarklxlong** [comment]
第一个问题：修改标签页上的小头像在/_includes/head.html 文件中的第18、19行。
第二个问题：关于你说的点击会出错的，我刚进了你的网站，点击后并没有发现问题，你遇到点击出错的问题可能是因为你的浏览器和Github的原因，在你每次提交修改后，使用同一个浏览器访问你的主页，你会发现根本没有修改成功，这是因为浏览器缓存的原因，你可以换个浏览器，或者清空一下缓存。

**Comment by yangqinj** [comment]
更换了浏览器以后确实可以了，谢谢。

**Comment by skylarklxlong** [comment]
@yangqinj 客气了: )
